version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - microservice
  server:
    build: ./server
    ports:
      - "3000:3000"
  client:
    build: ./client
  microservice:
    build: ./microservice
    ports:
      - "8080:8080"
